version: "3"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    volumes:
      - .:/usr/src/app
    env_file: ".env"
    networks:
      - appnet
    depends_on:
      - database
    ports:
      - "3001:3001"



  database:
    image: postgres:12
    networks:
      - appnet
    ports:
      - "5432:5432"
    volumes:
      - db_val:/var/lib/postgresql/data
    env_file: ".env"



    networks:
  appnet


volumes:
  db_val:
    driver: local
